### ISSUE TITLE
Mở dataset bằng labelImage hiện nhãn là 'dog'. 

### ISSUE THREAD

**Issue by CommandoHuan** [phamvanhanh6720/LicensePlateDetection#1]
Bạn ơi cho mình hỏi khi mình mở thư mục dataset bằng lablImage thì nó hiện lân nhãn là 'dog'. Xin hỏi bạn làm thế nào để đổi tên thành LicensePlate? Xin cám ơn.

**Comment by phamvanhanh6720** [comment]
https://github.com/tzutalin/labelImg#create-pre-defined-classes . Bạn đổi tên class theo hướng dẫn ở đây

**Comment by CommandoHuan** [comment]
> https://github.com/tzutalin/labelImg#create-pre-defined-classes . Bạn đổi tên class theo hướng dẫn ở đây

OK, cám ơn bạn nhiều.
